config/routes.rb
Forum::Application.routes.draw do

  resources :pms

  resources :profiles

  resources :posts

  resources :topics

  resources :albums

  resources :bands

  get "page/home"

  devise_for :users, :controllers => {:registrations => 'registrations'}

      root :to => 'bands#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :album_id, :band_id, :topic_name

  has_many :posts, :dependent => :destroy

  belongs_to :album
  belongs_to :band

  validates_length_of :topic_name, :minimum => 1, :maximum => 32, :allow_blank => false
  validates :topic_name, :uniqueness => true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter do
    if !user_signed_in?
      redirect_to "/page/home"
    end
  end

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, :notice => 'Topic was successfully created.' }
        format.json { render :json => @topic, :status => :created, :location => @topic }
      else
        format.html { redirect_to "/topics/new?album_id=#{@topic.album_id}&band_id=#{@topic.band_id}", :notice => @topic.errors.full_messages }
        format.json { render :json => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to "/albums/#{@topic.album_id}", :notice => 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to "/topics/#{@topic.id}/edit?band_id=#{@topic.band_id}&album_id=#{@topic.album_id}", :notice => @topic.errors.full_messages }
        format.json { render :json => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to "/albums/#{@topic.album.id}" }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic_name %><br />
    <%= f.text_field :topic_name, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.hidden_field :band_id, :value => (Band.find(params[:band_id])).id %>
  </div>
  <div class="field">
    <%= f.hidden_field :album_id, :value => (Album.find(params[:album_id])).id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<% provide(:band_path, "/bands/#{(Band.find(params[:band_id])).id}") %>
<% provide(:band_name, (Band.find(params[:band_id])).band_name) %>
<% provide(:album_path, "/albums/#{(Album.find(params[:album_id])).id}") %>
<% provide(:album_name, (Album.find(params[:album_id])).album_name) %>

<%= render 'form' %>

<%= link_to "Back", "/albums/#{@topic.album.id}", :class => "btn btn-mini" %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Topic name</th>
    <th>Band</th>
    <th>Album</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.topic_name %></td>
    <td><%= topic.band_id %></td>
    <td><%= topic.album_id %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<% provide(:band_path, "/bands/#{(Band.find(params[:band_id])).id}") %>
<% provide(:band_name, (Band.find(params[:band_id])).band_name) %>
<% provide(:album_path, "/albums/#{(Album.find(params[:album_id])).id}") %>
<% provide(:album_name, (Album.find(params[:album_id])).album_name) %>

<%= render 'form' %>

<%= link_to "Back", "/albums/#{(Album.find(params[:album_id])).id}", :class => "btn btn-mini" %>

app/views/topics/show.html.erb
<% provide(:band_path, "/bands/#{@topic.band.id}") %>
<% provide(:band_name, @topic.band.band_name) %>
<% provide(:album_path, "/albums/#{@topic.album.id}") %>
<% provide(:album_name, @topic.album.album_name) %>
<% provide(:topic_path, "/topics/#{@topic.id}") %>
<% provide(:topic_name, @topic.topic_name) %>

<table class="table table-bordered">
<tbody>
<% @topic.posts.each do |post| %>
  <tr>
    <td bgcolor="lightgray" rowspan="2" style="width: 1px; white-space: nowrap;"><h5><%= link_to post.user.username, "/profiles/#{post.user.id}" %></h5><% if post.user.admin? %>Administrator</br><% end %><br/><h6>Registered: <%= l post.user.created_at.localtime.to_date %><br/>Posts: <%= post.user.posts.count %></h6><br/><% if current_user.id != post.user_id %><%= link_to "Send PM", "/pms/new?id=#{post.user.username}", :class => "btn btn-mini", :target => "_blank" %><% end %></td>
    <td bgcolor="lightblue" colspan="2"><%= l post.created_at.localtime %></td>
  <tr>
    <td style="height: 100px; white-space: nowrap;"><%= simple_format h post.post_content %>
    <% if post.updated_at != post.created_at %>
      <hr>
      <div style="float:right;color:grey;">
        Last edited <%= l post.updated_at.localtime %>
      </div>
    <% end %>
    </td>
    <td bgcolor="lightgray" style="width: 1px; white-space: nowrap;"><% if current_user.admin? or current_user.id == post.user_id %><%= link_to 'Edit', "#{edit_post_path(post)}?band_id=#{@topic.band.id}&album_id=#{@topic.album.id}&topic_id=#{@topic.id}", :class => "btn btn-mini" %>&nbsp;<%= link_to 'Delete', post, :class => "btn btn-mini", :method => :delete, :data => { :confirm => 'Are you sure?' } %><% end %></td>
  </tr>
<% end %>
</tbody>  
</table>
</div>

<%= link_to "New post", {:controller => "posts", :action => "new", :band_id => @topic.band.id, :album_id => @topic.album.id, :topic_id => @topic.id }, :class => "btn btn-mini" %>
<%= link_to "Back", "/albums/#{@topic.album.id}", :class => "btn btn-mini" %>

<% if false %>
<br/><br/><br/><br/><br/>

<p>
  <b>Topic name:</b>
  <%= @topic.topic_name %>
</p>

<p>
  <b>Band:</b>
  <%= @topic.band_id %>
</p>

<p>
  <b>Album:</b>
  <%= @topic.album_id %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>
<% end %>