config/routes.rb
Forum::Application.routes.draw do

  resources :pms

  resources :profiles

  resources :posts

  resources :topics

  resources :albums

  resources :bands

  get "page/home"

  devise_for :users, :controllers => {:registrations => 'registrations'}

      root :to => 'bands#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :album_name, :band_id
  
  has_many :topics, :dependent => :destroy
  has_many :posts, :through => :topics, :dependent => :destroy

  belongs_to :band

  validates_length_of :album_name, :minimum => 1, :maximum => 32, :allow_blank => false
  validates :album_name, :uniqueness => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_filter do
    if !user_signed_in?
      redirect_to "/page/home"
    end
  end

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, :notice => 'Album was successfully created.' }
        format.json { render :json => @album, :status => :created, :location => @album }
      else
        format.html { redirect_to "/albums/new?band_id=#{@album.band_id}", :notice => @album.errors.full_messages }
        format.json { render :json => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to "/bands/#{@album.band_id}", :notice => 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to "/albums/#{@album.id}/edit?band_id=#{@album.band_id}", :notice => @album.errors.full_messages }
        format.json { render :json => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to "/bands/#{@album.band_id}" }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album_name %><br />
    <%= f.text_field :album_name, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.hidden_field :band_id, :value => (Band.find(params[:band_id])).id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<% provide(:band_path, "/bands/#{(Band.find(params[:band_id])).id}") %>
<% provide(:band_name, (Band.find(params[:band_id])).band_name) %>

<%= render 'form' %>

<%= link_to 'Back', "/bands/#{@album.band.id}", :class => "btn btn-mini" %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Album name</th>
    <th>Band</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.album_name %></td>
    <td><%= album.band_id %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<% provide(:band_path, "/bands/#{(Band.find(params[:band_id])).id}") %>
<% provide(:band_name, (Band.find(params[:band_id])).band_name) %>

<%= render 'form' %>

<%= link_to "Back", "/bands/#{(Band.find(params[:band_id])).id}", :class => "btn btn-mini" %>

app/views/albums/show.html.erb
<% provide(:band_path, "/bands/#{@album.band.id}") %>
<% provide(:band_name, @album.band.band_name) %>
<% provide(:album_path, "/albums/#{@album.id}") %>
<% provide(:album_name, @album.album_name) %>

<table class="table table-striped">  
<thead>  
  <tr>  
    <th>Topic Name</th>
    <th># of Posts</th>
    <th></th>   
  </tr>  
</thead>  
<tbody>
<% @album.topics.each do |topic| %>
  <tr>
    <td><%= link_to topic.topic_name, "/topics/#{topic.id}" %></td>
    <td><%= topic.posts.count %></td>
    <td><% if current_user.admin? %><%= link_to 'Edit', "#{edit_topic_path(topic)}?band_id=#{@album.band.id}&album_id=#{@album.id}", :class => "btn btn-mini" %>&nbsp;<%= link_to 'Delete', topic, :class => "btn btn-mini", :method => :delete, :data => { :confirm => 'Are you sure?' } %><% end %></td>
  </tr>
<% end %>
</tbody>  
</table>

<%= link_to "New topic", {:controller => "topics", :action => "new", :band_id => @album.band.id, :album_id => @album.id }, :class => "btn btn-mini" %>
<%= link_to "Back", "/bands/#{@album.band.id}", :class => "btn btn-mini" %>

<% if false %>
<br/><br/><br/><br/><br/>

<p>
  <b>Album name:</b>
  <%= @album.album_name %>
</p>

<p>
  <b>Band:</b>
  <%= @album.band_id %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>
<% end %>