config/routes.rb
Forum::Application.routes.draw do

  resources :pms

  resources :profiles

  resources :posts

  resources :topics

  resources :albums

  resources :bands

  get "page/home"

  devise_for :users, :controllers => {:registrations => 'registrations'}

      root :to => 'bands#index'

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :band_name

  has_many :albums, :dependent => :destroy
  has_many :topics, :through => :albums, :dependent => :destroy
  has_many :posts, :through => :topics, :dependent => :destroy

  validates_length_of :band_name, :minimum => 1, :maximum => 32, :allow_blank => false
  validates :band_name, :uniqueness => true
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_filter do
    if !user_signed_in?
      redirect_to "/page/home"
    end
  end

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bands }
    end
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
    @band = Band.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @band }
    end
  end

  # GET /bands/new
  # GET /bands/new.json
  def new
    @band = Band.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @band }
    end
  end

  # GET /bands/1/edit
  def edit
    @band = Band.find(params[:id])
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(params[:band])

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, :notice => 'Band was successfully created.' }
        format.json { render :json => @band, :status => :created, :location => @band }
      else
        format.html { redirect_to "/bands/new", :notice => @band.errors.full_messages }
        format.json { render :json => @band.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bands/1
  # PUT /bands/1.json
  def update
    @band = Band.find(params[:id])

    respond_to do |format|
      if @band.update_attributes(params[:band])
        format.html { redirect_to bands_url, :notice => 'Band was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to "/bands/#{@band.id}/edit", :notice => @band.errors.full_messages }
        format.json { render :json => @band.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band = Band.find(params[:id])
    @band.destroy

    respond_to do |format|
      format.html { redirect_to bands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :band_name %><br />
    <%= f.text_field :band_name, :autofocus => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', bands_path, :class => "btn btn-mini" %>

app/views/bands/index.html.erb
<table class="table table-striped">  
<thead>  
  <tr>  
    <th>Band name</th>  
    <th># of Albums</th>  
    <th># of Topics</th>  
    <th># of Posts</th> 
    <th></th> 
  </tr>  
</thead>  
<tbody>
<% @bands.each do |band| %>
  <tr>
    <td><%= link_to band.band_name, band %></td>
    <td><%= band.albums.count %></td>
    <td><%= band.topics.count %></td>
    <td><%= band.posts.count %></td>
    <td><% if current_user.admin? %><%= link_to 'Edit', edit_band_path(band), :class => "btn btn-mini" %>&nbsp;<%= link_to 'Delete', band, :class => "btn btn-mini", :method => :delete, :data => { :confirm => 'Are you sure?' } %><% end %></td>
  </tr>
<% end %>
</tbody>  
</table>
<% if current_user.admin? %><%= link_to "New band", '/bands/new', :class => "btn btn-mini" %><% end %>

<% if false %>
<br/><br/><br/><br/><br/>

<table>
  <tr>
    <th>Band name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bands.each do |band| %>
  <tr>
    <td><%= band.band_name %></td>
    <td><%= link_to 'Show', band %></td>
    <td><%= link_to 'Edit', edit_band_path(band) %></td>
    <td><%= link_to 'Destroy', band, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Band', new_band_path %>
<% end %>

app/views/bands/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', bands_path, :class => "btn btn-mini" %>

app/views/bands/show.html.erb
<% provide(:band_path, "/bands/#{@band.id}") %>
<% provide(:band_name, @band.band_name) %>

<table class="table table-striped">  
<thead>  
  <tr>  
    <th>Album name</th> 
    <th># of Topics</th>  
    <th># of Posts</th>
    <th></th> 
  </tr>  
</thead>  
<tbody>
<% @band.albums.each do |album| %>
  <tr>
    <td><%= link_to album.album_name, "/albums/#{album.id}" %></td>
    <td><%= album.topics.count %></td>
    <td><%= album.posts.count %></td>
    <td><% if current_user.admin? %><%= link_to 'Edit', "#{edit_album_path(album)}?band_id=#{@band.id}", :class => "btn btn-mini" %>&nbsp;<%= link_to 'Delete', album, :class => "btn btn-mini", :method => :delete, :data => { :confirm => 'Are you sure?' } %><% end %></td>
  </tr>
<% end %>
</tbody>  
</table>
<% if current_user.admin? %><%= link_to "New album", {:controller => "albums", :action => "new", :band_id => @band.id }, :class => "btn btn-mini" %><% end %>
<%= link_to "Back", '/bands/', :class => "btn btn-mini" %>

<% if false %>
<br/><br/><br/><br/><br/>

<p>
  <b>Band name:</b>
  <%= @band.band_name %>
</p>


<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>
<% end %>